version: "3.8"

services:
  tuna:
    image: yuccastream/tuna:latest
    command: http 8081 --subdomain=irkdoskatmatest
    restart: always
    network_mode: "host"
    env_file:
      - .env.bot
    depends_on:
      - bot
  bot:
    build:
      context: ../../
      dockerfile: deploy/Dockerfile.bot
    env_file:
      - .env.bot
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env.bot
    ports:
      - "1234:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: