version: "3.8"

services:
  tuna:
    image: yuccastream/tuna:latest
    command: http 8081 --subdomain=irkdoskatmatest
    restart: always
    network_mode: "host"
    env_file:
      - .env.bot
    depends_on:
      - bot
      - frontend
  frontend:
    build:
      context: ../../
      dockerfile: deploy/Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
  backend:
    build:
      context: ../../
      dockerfile: deploy/Dockerfile.backend
    env_file:
      - .env.bot
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - minio
  bot:
    build:
      context: ../../
      dockerfile: deploy/Dockerfile.bot
    env_file:
      - .env.bot
    depends_on:
      - db
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env.bot
    ports:
      - "1234:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-13T20-26-02Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: